FROM ebassi/endlessci:sdk
ADD . /home/jhbuildci/source/@MODULE@
RUN chown -hR jhbuildci /home/jhbuildci/source/@MODULE@/* /home/jhbuildci/source/@MODULE@/.*

USER jhbuildci
RUN endless-build-module @MODULE@
